# Generated by Django 4.2.3 on 2023-08-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tickets',
            new_name='Ticket',
        ),
    ]
