# Generated by Django 4.2.3 on 2023-08-13 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_posts_vip_user_alter_posts_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='vip_user',
            new_name='vip_content',
        ),
    ]
